server:
  port: 0
spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
uri:
  base: http://localhost