server:
  port: ${PORT:0}
spring:
  application:
    name: users-ws
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
uri:
  base: http://localhost
  gateway_ip: 192.168.56.1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}